workspace = { members = ["src/tickets"] }
[package]
name = "otus_algo_hw_02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
